"""initial

Revision ID: 1c64b1a5f333
Revises:
Create Date: 2023-11-19 17:35:41.051116

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c64b1a5f333"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Urls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("shortened_url", sa.Uuid(), nullable=False),
        sa.Column("times_clicked", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Urls_id"), "Urls", ["id"], unique=True)
    op.create_index(
        op.f("ix_Urls_shortened_url"), "Urls", ["shortened_url"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Urls_shortened_url"), table_name="Urls")
    op.drop_index(op.f("ix_Urls_id"), table_name="Urls")
    op.drop_table("Urls")
    # ### end Alembic commands ###
