"""initial

Revision ID: 7160161aa474
Revises:
Create Date: 2023-11-13 20:13:51.769753

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7160161aa474"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Urls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("shortened_url", sa.UUID(), nullable=True),
        sa.Column("times_clicked", sa.Integer(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Urls_shortened_url"), "Urls", ["shortened_url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Urls_shortened_url"), table_name="Urls")
    op.drop_table("Urls")
    # ### end Alembic commands ###
